const routeNames = {
  // BASE_URL: "https://projectapi.calibrewebsol.com/api/",
  LOGIN: "/login",
  FORGOTPASSWORD: "/ForgotPassword",
  RESETPASSWORD: "/reset-password",
  SIGNUP: "/signup",
  DASHBOARD: "/",
  TITLE: "/title",
  CREATETITLE: "/title/create",
  PASSWORDRESET: "/PasswordReset",
  CREATECASE: "/createcase",
  EDITCASE: "/case/edit",
  OFFICEUNIT: "/officeunit",
  OFFICELEVEL: "/officelevel",
  CREATEOFFICEUNIT: "/createofficeunit",
  CREATEOFFICELEVEL: "/createofficelevel",
  INSPECTIONTYPE: "/inspectiontype",
  CREATEINSPECTIONTYPE: "/createinspectiontype",
  INSTALLATIONADDRESS: "/installationaddress",
  CREATEINSTALLATIONADDRESS: "/createinstallationaddress",
  SUBJECTTYPE: "/subjecttype",
  CREATESUBJECTTYPE: "/createsubjecttype",
  SUBJECT: "/subject",
  CREATETHESUBJECT: "/createthesubject",
  CREATEINSPECTION: "/inspection/create",
  EDITINSPECTION: "/inspection/edit",
  EDITTERRITORY: "/ territory/edit",
  INSPECTION: "/inspection",
  OFFICE: "/office",
  CREATEOFFICE: "/createoffice",
  EMPLOYEE: "/employee",
  DDOTYPE: "/ddotype",
  CREATEDDOTYPE: "/createddotype",
  CASEMANAGER: "/casemanager",
  CREATESTATE: "/createstate",
  CONTACT: "/contact",
  CREATECONTACT: "/createcontact",
  INSPECTIONCERTIFICATE: "/inspectioncertificate",
  MODULE: "/module",
  CREATEMODULE: "/CreateModule",
  USERMODULE: "/usermodule",
  DESIGNATION: "/designation",
  DISTRICT: "/district",
  OFFICETYPE: "/officetype",
  RTIDESIGNATION: "/rtidesignation",
  STATE: "/state",
  CREATEDESIGNATION: "/createdesignation",
  CREATEDISTRICT: "/createdistrict",
  CREATEOFFICETYPE: "/createofficetype",
  CREATERTIDESIGNATION: "/creatertidesignation",
  CREATEUSER: "/user/create",
  USER: "/user",
  ROLE: "/role",
  CREATEROLE: "/createrole",
  EDITUSER: "/ user/edit",
  OFFICEACCOUNTDETAILS:"/officeaccountdetails",
  CREATEOFFICEACCOUNTDETAILS:"/createofficeaccountdetails",
  OTHEROFFICE:"/otheroffice",
  // EDITUSER: "/ user/edit",
};
export default routeNames;
